"""
Map Agent Schemas
Pydantic models for agent request/response
"""
from pydantic import BaseModel, Field


class MapAgentRequest(BaseModel):
    """Map agent request"""
    prompt: str = Field(
        ...,
        min_length=3,
        max_length=500,
        description="Natural language search request",
        examples=[
            "List the best restaurants in Kadıköy",
            "Where are the open cafes in Beşiktaş?",
            "Find pizza restaurants near Taksim",
        ],
    )
    model_name: str = Field(
        ...,
        min_length=3,
        max_length=100,
        description="OpenRouter model name to use",
        examples=[
            "openai/gpt-4o-mini",
            "anthropic/claude-3.5-sonnet",
        ],
    )


class MapAgentResponse(BaseModel):
    """Map agent response"""
    query: str = Field(..., description="User's original request")
    response: str = Field(..., description="Place list generated by the agent")
    center: dict | None = Field(
        default=None,
        description="Map center with lat/lon and optional label",
        examples=[{"lat": 41.0082, "lon": 28.9784, "label": "Istanbul"}],
    )
    places: list[dict] | None = Field(
        default=None,
        description="Structured places with coordinates",
        examples=[[{"name": "Cafe", "lat": 41.01, "lon": 28.98, "address": "Kadikoy"}]],
    )
